#!/usr/bin/env python3
from src import resistere_config
from src import pv

def main():
    config = resistere_config.read_config()
    print(config)

    surplus_power = pv.read_current_energy_surplus(config)

if __name__ == "__main__":
    main()
