#!/usr/bin/env python3
from src import resistere_config
from src import huh

def main():
    config = resistere_config.read_config()
    print(config)

    huh.persist_values_to_file(config)

if __name__ == "__main__":
    main()
